[package]
name = "nirion-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
nirion-oci-lib = { version = "0.1.0", path = "../nirion-oci-lib" }
anyhow = "1.0.101"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
